ruleset=DIRECT,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Lan/Lan.list
ruleset=DIRECT,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Direct/Direct.list
ruleset=DIRECT,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Download/Download.list
ruleset=REJECT,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Advertising/Advertising.list
ruleset=REJECT,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/EasyPrivacy/EasyPrivacy.list
ruleset=YouTube,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/YouTube/YouTube.list
ruleset=Spotify,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Spotify/Spotify.list
ruleset=Streaming,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/GlobalMedia/GlobalMedia.list
ruleset=Telegram,[]GEOIP,TELEGRAM
ruleset=Microsoft,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Microsoft/Microsoft.list
ruleset=Proxy,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Proxy/Proxy.list
ruleset=Apple,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Apple/Apple.list
ruleset=DIRECT,https://raw.githubusercontent.com/VirgilClyne/GetSomeFries/main/ruleset/ASN.China.list
ruleset=DIRECT,[]GEOIP,CN
ruleset=Final,[]FINAL

custom_proxy_group=Hong Kong`select`(香港|HK|Hong)
;custom_proxy_group=Taiwan`select`(台湾|TW|Tai)
custom_proxy_group=Japan`select`(日本|JP|Jap)
custom_proxy_group=Singapore`select`(新加坡|SG|Singa)
custom_proxy_group=United States`select`(美国|US)
;custom_proxy_group=Others`select`GCX`^((?!香港|HK|Hong|台湾|TW|Tai|日本|JP|Jap|新加坡|SG|Singa|美国|US).)*$
custom_proxy_group=Proxy`select`[]Hong Kong`[]Japan`[]Singapore`[]United States`[]DIRECT
custom_proxy_group=YouTube`select`[]Hong Kong`[]Japan`[]Singapore`[]United States`[]DIRECT
custom_proxy_group=Spotify`select`[]Hong Kong`[]Japan`[]Singapore`[]United States`[]DIRECT
custom_proxy_group=Streaming`select`[]Hong Kong`[]Japan`[]Singapore`[]United States`[]DIRECT
custom_proxy_group=Telegram`select`[]Hong Kong`[]Japan`[]Singapore`[]United States`[]DIRECT
custom_proxy_group=Microsoft`select`[]Hong Kong`[]Japan`[]Singapore`[]United States`[]DIRECT
custom_proxy_group=Apple`select`[]Hong Kong`[]Japan`[]Singapore`[]United States`[]DIRECT
custom_proxy_group=Final`select`[]Hong Kong`[]Japan`[]Singapore`[]United States`[]DIRECT
